### ISSUE TITLE
Optimize data usage

### ISSUE THREAD

**Issue by simensrostad** [hello-nrfcloud/firmware#237]

**Comment by coderbyheart** [comment]
on preview18:

Data usage is pretty high, I had it running for 6 hours now and it already used 1.6 MB of data with hourly publication interval:

![image](https://github.com/hello-nrfcloud/firmware/assets/188915/59f4190d-f243-42e7-8b21-e36ae5ecea9e)

![image](https://github.com/hello-nrfcloud/firmware/assets/188915/2af1f823-a6dd-40c1-84df-6e791a0fafbf)

There were quite a few crashes, so this may have caused the high data usage.

![image](https://github.com/hello-nrfcloud/firmware/assets/188915/20c4b12d-9f17-41e3-9fa0-d2495f0a1f0c)

Memfault: https://app.memfault.com/organizations/nordic-semiconductor-asafbpk/projects/hello-nrfcloud-com/devices/355025930003841?since=2024-07-04T11%3A21%3A54.729Z&until=2024-07-05T19%3A30%3A29.797Z

**Comment by coderbyheart** [comment]
Did another test today.

Usage was around 200 KB / Hour. But with frequent reboots.

![Screenshot_20240706_084036](https://github.com/hello-nrfcloud/firmware/assets/188915/79a5bc62-e88c-40f6-adb1-f0a0300eaeb3)
![Screenshot_20240706_084001](https://github.com/hello-nrfcloud/firmware/assets/188915/70f45cd3-034e-487b-988b-9a69ae7bcf46)

**Comment by coderbyheart** [comment]
With version 20 the data usage per day is around 1 MB.

| Time                |    Bytes |
| ------------------- | -------: |
| 2024-07-13 00:01:43 |     4218 |
| 2024-07-13 01:37:39 |    58605 |
| 2024-07-13 01:52:39 |    30767 |
| 2024-07-13 02:07:39 |     2593 |
| 2024-07-13 02:52:39 |     9074 |
| 2024-07-13 03:07:39 |    31167 |
| 2024-07-13 03:43:46 |    56303 |
| 2024-07-13 05:48:23 |    39268 |
| 2024-07-13 06:38:12 |    79346 |
| 2024-07-13 06:53:12 |    30234 |
| 2024-07-13 07:18:28 |    44319 |
| 2024-07-13 08:21:36 |    59574 |
| 2024-07-13 09:06:36 |     6179 |
| 2024-07-13 09:21:36 |     6581 |
| 2024-07-13 09:36:36 |    24329 |
| 2024-07-13 10:06:36 |     6338 |
| 2024-07-13 10:36:36 |    18032 |
| 2024-07-13 10:51:36 |    16005 |
| 2024-07-13 11:06:36 |     6096 |
| 2024-07-13 11:51:36 |    49247 |
| 2024-07-13 12:06:36 |     6096 |
| 2024-07-13 12:51:36 |     3961 |
| 2024-07-13 13:06:36 |    47659 |
| 2024-07-13 14:06:37 |    15275 |
| 2024-07-13 14:21:37 |    17855 |
| 2024-07-13 15:06:37 |     6096 |
| 2024-07-13 15:21:37 |    44748 |
| 2024-07-13 15:36:37 |     4201 |
| 2024-07-13 16:06:37 |     6096 |
| 2024-07-13 16:36:37 |    10227 |
| 2024-07-13 16:51:37 |      465 |
| 2024-07-13 17:06:37 |     6096 |
| 2024-07-13 17:36:37 |     6867 |
| 2024-07-13 17:51:37 |    20793 |
| 2024-07-13 18:06:37 |     6096 |
| 2024-07-13 18:51:37 |    16171 |
| 2024-07-13 19:06:37 |    31626 |
| 2024-07-13 20:06:37 |    47958 |
| 2024-07-13 20:21:37 |      248 |
| 2024-07-13 21:06:37 |    10058 |
| 2024-07-13 21:21:37 |    30110 |
| 2024-07-13 21:36:37 |      513 |
| 2024-07-13 22:06:37 |     6097 |
| 2024-07-13 22:21:37 |     3769 |
| 2024-07-13 22:36:37 |    71754 |
| 2024-07-13 23:06:37 |     6097 |
| 2024-07-13 23:36:37 |     6834 |
| 2024-07-13 23:51:37 |    18688 |
| Total               | 10130729 |

**Comment by balaji-nordic** [comment]
@coderbyheart  I just released https://github.com/hello-nrfcloud/firmware/releases/tag/v2.0.0-preview21 . This has a couple of improvements related to data usage. Can you test it out and see how the data usage graph looks like?

**Comment by coderbyheart** [comment]
Yes, I have flashed it to my device and will let it run over the weekend outdoors.

**Comment by balaji-nordic** [comment]
Found another bug that will still result in higher data consumption that needed. Will fix early next week

**Comment by coderbyheart** [comment]
Version 21 has gotten much worse.

With version 21 the data usage per day is around 5.5 MB.

| Time                |   Bytes |
| ------------------- | ------: |
| 2024-08-03 08:44:39 |   19217 |
| 2024-08-03 08:59:39 |  146297 |
| 2024-08-03 09:59:39 |   51475 |
| 2024-08-03 10:03:02 |   46381 |
| 2024-08-03 10:07:23 |   62173 |
| 2024-08-03 10:22:26 |  161452 |
| 2024-08-03 11:21:27 |   28960 |
| 2024-08-03 11:31:19 |  138066 |
| 2024-08-03 11:33:12 |   52156 |
| 2024-08-03 11:48:14 |  143435 |
| 2024-08-03 12:04:54 |  111355 |
| 2024-08-03 13:04:54 |   37324 |
| 2024-08-03 13:19:54 |  100689 |
| 2024-08-03 13:34:54 |    6061 |
| 2024-08-03 14:19:54 |   36224 |
| 2024-08-03 14:34:54 |  144285 |
| 2024-08-03 14:49:54 |  142681 |
| 2024-08-03 15:04:54 |  141808 |
| 2024-08-03 15:19:54 |   23121 |
| 2024-08-03 15:34:54 |    6091 |
| 2024-08-03 16:19:54 |  111272 |
| 2024-08-03 16:34:54 |  143244 |
| 2024-08-03 16:49:54 |  142433 |
| 2024-08-03 17:04:54 |   56089 |
| 2024-08-03 17:34:54 |    6092 |
| 2024-08-03 18:04:54 |   82712 |
| 2024-08-03 18:19:54 |  139584 |
| 2024-08-03 18:34:54 |  146332 |
| 2024-08-03 18:49:54 |  141321 |
| 2024-08-03 19:04:54 |  140976 |
| 2024-08-03 19:19:54 |  138936 |
| 2024-08-03 19:34:54 |   71717 |
| 2024-08-03 20:34:54 |   70668 |
| 2024-08-03 20:49:54 |   86802 |
| 2024-08-03 21:34:54 |    6092 |
| 2024-08-03 21:49:54 |   38145 |
| 2024-08-03 22:34:54 |    6092 |
| 2024-08-03 22:49:54 |   16692 |
| 2024-08-03 23:04:54 |  139619 |
| 2024-08-03 23:19:54 |  140080 |
| 2024-08-03 23:34:54 |   44525 |
| 2024-08-04 00:34:54 |  106060 |
| 2024-08-04 00:49:54 |    9657 |
| 2024-08-04 01:34:55 |    6132 |
| 2024-08-04 01:49:55 |  128228 |
| 2024-08-04 02:04:55 |  128401 |
| 2024-08-04 02:34:55 |    6132 |
| 2024-08-04 03:04:55 |   10620 |
| 2024-08-04 03:19:55 |  141440 |
| 2024-08-04 03:34:55 |  118837 |
| 2024-08-04 04:34:55 |   33044 |
| 2024-08-04 04:49:55 |   50682 |
| 2024-08-04 05:34:55 |    6132 |
| 2024-08-04 05:49:55 |   86792 |
| 2024-08-04 06:04:55 |  137976 |
| 2024-08-04 06:19:55 |  138472 |
| 2024-08-04 06:34:55 |  147076 |
| 2024-08-04 06:49:55 |   88874 |
| 2024-08-04 07:34:55 |    6132 |
| 2024-08-04 07:49:55 |   51184 |
| 2024-08-04 08:04:55 |  128704 |
| 2024-08-04 08:19:55 |  131424 |
| 2024-08-04 08:34:55 |  144852 |
| 2024-08-04 08:49:55 |  142433 |
| Total               | 5417958 |

**Comment by coderbyheart** [comment]
![image](https://github.com/user-attachments/assets/24ab0cb1-8e7d-4f0d-aa6e-c129c692b50b)

**Comment by balaji-nordic** [comment]
More improvements done in https://github.com/hello-nrfcloud/firmware/releases/tag/v2.0.0-preview22 . It seems to work well when we tested today. Can you please test it out @coderbyheart ?

**Comment by coderbyheart** [comment]
I have set it up outside the office with GNSS enabled.

**Comment by coderbyheart** [comment]
Already looks like a massive difference, but will let it run for 24 hours.

![image](https://github.com/user-attachments/assets/f55053bf-a5d6-406e-a16c-d6c3c6025316)

**Comment by coderbyheart** [comment]
Looks better, however I still think that ~250 KB / day is too high. I'd say the target should be max 100 KB /day. 

![image](https://github.com/user-attachments/assets/f5373abe-1cba-4a54-a31e-1e461cc18006)

| Time   |  Bytes |
| ------------------- | ------: |
| 2024-08-06 10:50:47 | 16712 |
| 2024-08-06 11:05:47 | 44395 |
| 2024-08-06 12:05:47 | 7419 |
| 2024-08-06 13:05:47 | 10169 |
| 2024-08-06 14:05:47 | 7461 |
| 2024-08-06 15:05:47 | 10169 |
| 2024-08-06 16:05:47 | 7461 |
| 2024-08-06 17:05:47 | 10169 |
| 2024-08-06 18:05:47 | 7461 |
| 2024-08-06 19:05:48 | 10169 |
| 2024-08-06 20:05:48 | 7421 |
| 2024-08-06 21:05:48 | 10169 |
| 2024-08-06 22:05:48 | 7461 |
| 2024-08-06 23:05:48 | 10169 |
| 2024-08-07 00:05:48 | 7213 |
| 2024-08-07 00:20:48 | 248 |
| 2024-08-07 01:05:48 | 6101 |
| 2024-08-07 01:20:48 | 4068 |
| 2024-08-07 02:05:48 | 6061 |
| 2024-08-07 02:20:48 | 1360 |
| 2024-08-07 03:05:48 | 6101 |
| 2024-08-07 03:20:48 | 4068 |
| 2024-08-07 04:05:48 | 6101 |
| 2024-08-07 04:20:48 | 1360 |
| 2024-08-07 05:05:48 | 6101 |
| 2024-08-07 05:20:48 | 4068 |
| 2024-08-07 06:05:48 | 6101 |
| 2024-08-07 06:20:48 | 1360 |
| 2024-08-07 07:05:48 | 6101 |
| 2024-08-07 07:20:48 | 4068 |
| 2024-08-07 08:05:48 | 6101 |
| 2024-08-07 08:20:48 | 1360 |
| 2024-08-07 09:05:48 | 6101 |
| 2024-08-07 09:20:48 | 4268 |
| 2024-08-07 10:05:48 | 6061 |
| 2024-08-07 10:20:48 | 2210 |
| 2024-08-07 11:05:48 | 6101 |
| Total | 269487 |

**Comment by simensrostad** [comment]
We should poll for FOTA updates less regularly. Right now that happens every update.
We could have a guard that prevents FOTA updates to happen no more than every minute (Kconfigurable) or something in that realm.

That will bring consumption down to ~100k I belive.

**Comment by simensrostad** [comment]
Added this in v2.0.0-preview27, please test

**Comment by simensrostad** [comment]
https://github.com/hello-nrfcloud/firmware/pull/269

PR that makes the firmware poll for FOTA every hour. Button presses still polls for FOTA async

**Comment by coderbyheart** [comment]
Testing [v2.0.0-preview27](https://github.com/hello-nrfcloud/firmware/releases/tag/v2.0.0-preview27) now.

**Comment by simensrostad** [comment]
Nice, the next release will be even better. Ill make one before the end of day

**Comment by coderbyheart** [comment]
This version does not seem to enter low-power mode, it keeps sending GNSS updates every 30 seconds:

```
{
      "0": 63.4214330884501,
      "1": 10.4365674223562,
      "3": 5.71514558792114,
      "6": "GNSS",
      "99": 1723125332
    },
    {
      "0": 63.4214441987205,
      "1": 10.436631094311,
      "3": 9.91567134857178,
      "6": "GNSS",
      "99": 1723125363
    },
    {
      "0": 63.4213770784759,
      "1": 10.4365441117388,
      "3": 63.8581848144531,
      "6": "GNSS",
      "99": 1723125394
    },
    {
      "0": 63.4213611280096,
      "1": 10.4365166212979,
      "3": 70.4940948486328,
      "6": "GNSS",
      "99": 1723125425
    },
    {
      "0": 63.4215303104333,
      "1": 10.4365549831392,
      "3": 9.47572803497315,
      "6": "GNSS",
      "99": 1723125455
    },
    {
      "0": 63.4213666235805,
      "1": 10.436736534168,
      "3": 9.6929874420166,
      "6": "GNSS",
      "99": 1723125486
    },
    {
      "0": 63.4214665529458,
      "1": 10.4365663855526,
      "3": 6.3304500579834,
      "6": "GNSS",
      "99": 1723125516
    },
    {
      "0": 63.4215065723531,
      "1": 10.4365249572112,
      "3": 6.44057655334473,
      "6": "GNSS",
      "99": 1723125547
    },
    {
      "0": 63.42151228638,
      "1": 10.4365739818016,
      "3": 7.32491779327393,
      "6": "GNSS",
      "99": 1723125577
    },
```

**Comment by coderbyheart** [comment]
Stopping the test because this drains the data I have on the SIM.

![image](https://github.com/user-attachments/assets/8eebb344-fcff-4787-9a7f-bee0f89bc2fb)

**Comment by simensrostad** [comment]
Are you in the default low power mode?

**Comment by coderbyheart** [comment]
Yes, I didn't change the device config.

It lasted much longer than 10 minutes. I think I left it running for more than 1 hour.

**Comment by simensrostad** [comment]
Looking into it, cc @balaji-nordic

**Comment by simensrostad** [comment]
@coderbyheart did you update the config after the device was powered? What updates did you do?

**Comment by coderbyheart** [comment]
No, Just flashed the fw.

**Comment by simensrostad** [comment]
The issue has been resolved in preview30.

**Comment by coderbyheart** [comment]
Ok, I'll test once more.

**Comment by coderbyheart** [comment]
Not fixed:

![image](https://github.com/user-attachments/assets/a5c277bd-02c4-474f-9b4e-723ce97ef908)

Still doing GNSS fixes after 10 minutes.

![image](https://github.com/user-attachments/assets/4fb591bb-a7e6-497e-8ad7-e862645d5ecc)

**Comment by coderbyheart** [comment]
Between 2024-08-12T08:25:33.541Z and 2024-08-12T08:44:32.478Z the device did **94** GNSS fixes. This is way too much. We do not need a GNSS every 10 seconds.
Once per minute is enough.
[results.csv](https://github.com/user-attachments/files/16579438/results.csv)

**Comment by simensrostad** [comment]
This is because location is sampled together with all other sources. (bat, environ, etc...). So when in real time mode, it will happen every 20 seconds for the first 10 minutes. 94 sounds a bit much, I would expect around ~30. (will look into this)

If we are to make an distinction between the different sample sources, we need to update the device description a bit. ATM the behavior only document "update interval", which I thought encapsulated all sample sources.

![image](https://github.com/user-attachments/assets/10fe6f15-4547-4d07-bde0-65f9a72228e9)

**Comment by coderbyheart** [comment]
Note that the description above also does not mention that real-time mode means sampling of location, it's just "update interval".

We need the 20-second updates for things that are likely to change (e.g. configuration, button press), and it's there so users can interact with their device and they get notified quickly when the device comes online.

But location is something that is unlikely to change within 20 seconds, especially not SCELL, MCELL and WIFI, so we do not need to spam this to the cloud.

So maybe consider aligning the location updates with the FOTA polling, and call this a "low resolution" timer.

**Comment by simensrostad** [comment]
Yeah, a minute is excessive indeed. Triggering location updates at the same time as the FOTA polling sounds reasonable.
What about when the users toggles real-time mode? Should we keep location triggers at 20 seconds to benefit users that want a bit more frequent location updates? Driving, running, etc... This is at least an active choice the user makes, and they should expect higher data / power usage.

**Comment by coderbyheart** [comment]
> Should we keep location triggers at 20 seconds to benefit users that want a bit more frequent location updates? Driving, running, etc... This is at least an active choice the user makes, and they should expect higher data / power usage.

No, because the OOB is not intended for that.

**Comment by simensrostad** [comment]
Would it be an alternative to increase the data sample interval in real-time mode to 1 minute in general?
To be clear, data sampling (sampling sensors and location) would occur every 1 minute while polling cloud would still occur every 20 seconds. As it is today.

**Comment by simensrostad** [comment]
As location, battery and environmental should change that often either.

**Comment by coderbyheart** [comment]
Yes, that sounds good.

**Comment by simensrostad** [comment]
Regarding the real-time mode settings.

![image](https://github.com/user-attachments/assets/77585ba8-d371-482e-bab7-48e42d05e238)

When the user select 20 seconds, could we make that 1 minute instead?
We use the update interval as the timeout for data sampling.

Regardless of this interval, we enter the 10 minute window where we poll the cloud every 20 seconds.

**Comment by simensrostad** [comment]
So update interval is bound to how often the device sends new sensor data.

**Comment by coderbyheart** [comment]
The excessive GNSS fixes no longer appear.

**Comment by coderbyheart** [comment]
Average daily use (without the usage spike after boot) looks to be >200 KB / day.

**Comment by simensrostad** [comment]
Should be improved after https://github.com/hello-nrfcloud/firmware/pull/281

**Comment by coderbyheart** [comment]
It seems that the chart reports higher values, when I fetch the usage via the API, this is what I get, and when I should believe this, we're actually on <100 KB usage / day when the device runs for a longer time.

| Time                |  Bytes |
| ------------------- | -----: |
| 2024-08-12 14:27:16 |  39409 |
| 2024-08-12 15:27:17 |   7459 |
| 2024-08-12 16:27:17 |   7459 |
| 2024-08-12 17:27:17 |  10159 |
| 2024-08-12 18:27:17 |   7461 |
| 2024-08-12 19:27:17 |  10169 |
| 2024-08-12 20:27:17 |   7461 |
| 2024-08-12 21:27:17 |  10169 |
| 2024-08-12 22:27:17 |   7461 |
| 2024-08-12 23:27:17 |  10169 |
| 2024-08-13 00:27:18 |   7213 |
| 2024-08-13 00:42:18 |    248 |
| 2024-08-13 01:27:18 |   6101 |
| 2024-08-13 01:42:18 |   4068 |
| 2024-08-13 02:27:18 |   6101 |
| 2024-08-13 02:42:18 |   1360 |
| 2024-08-13 03:27:18 |   6101 |
| 2024-08-13 03:42:18 |   4068 |
| 2024-08-13 04:27:18 |   6101 |
| 2024-08-13 04:42:18 |   1360 |
| 2024-08-13 05:27:18 |   6101 |
| 2024-08-13 05:42:18 |   4116 |
| 2024-08-13 06:27:18 |   6101 |
| 2024-08-13 06:42:18 |   1360 |
| 2024-08-13 07:27:18 |   6101 |
| 2024-08-13 07:42:18 |   4068 |
| 2024-08-13 08:27:18 |   6061 |
| 2024-08-13 08:42:18 |   1360 |
| 2024-08-13 09:27:18 |   6101 |
| 2024-08-13 09:42:18 |   4337 |
| 2024-08-13 10:27:18 |   6101 |
| 2024-08-13 10:42:18 |   1360 |
| 2024-08-13 11:27:18 |   6101 |
| 2024-08-13 11:42:18 |   4068 |
| 2024-08-13 12:27:18 |   6101 |
| 2024-08-13 12:42:18 |   1360 |
| 2024-08-13 13:27:18 |   6101 |
| 2024-08-13 13:42:18 |   4333 |
| 2024-08-13 14:27:18 |   6101 |
| Total               | 247429 |

**Comment by simensrostad** [comment]
Please try [v2.0.0-preview34](https://github.com/hello-nrfcloud/firmware/releases/tag/v2.0.0-preview34)

**Comment by coderbyheart** [comment]
Looks good now.
